name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      # 发送开始构建的消息到 Slack
      - name: Send Build Start Message to Slack Channel
        uses: slackapi/slack-github-action@v1.17.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "《彷徨之街》宣传网站测试页开始通过 Azure 静态网站服务进行构建",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "===================\n《彷徨之街》宣传网站测试页开始进行构建\n===================\n\n构建基于: \n提交 SHA: ${{ steps.commit.outputs.sha }}\n提交消息: ${{ steps.commit.outputs.msg }} (${{ steps.commit.outputs.author }})"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_FIELD_05C532F00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
      # 发送构建成功的消息到 Slack
      - name: Send Build End Message to Slack Channel
        uses: slackapi/slack-github-action@v1.17.0
        if: ${{ success() }}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "《彷徨之街》宣传网站测试页通过 Azure 静态网站服务构建成功",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "===================\n《彷徨之街》宣传网站测试页构建成功\n===================\n\n构建基于: \n提交 SHA: ${{ steps.commit.outputs.sha }}\n提交消息: ${{ steps.commit.outputs.msg }} (${{ steps.commit.outputs.author }})\n当前静态页面的地址: ${{ steps.builddeploy.outputs.static_web_app_url }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
      # 发送构建失败的消息到 Slack
      - name: Send Build End Message to Slack Channel
        uses: slackapi/slack-github-action@v1.17.0
        if: ${{ failure() }}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "《彷徨之街》宣传网站测试页通过 Azure 静态网站服务构建失败",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "===================\n《彷徨之街》宣传网站测试页构建失败\n===================\n\n构建基于: \n提交 SHA: ${{ steps.commit.outputs.sha }}\n提交消息: ${{ steps.commit.outputs.msg }} (${{ steps.commit.outputs.author }})"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_FIELD_05C532F00 }}
          action: "close"
