name: 构建并上传至 Azure Blob

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - stable

jobs:
  start_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: 发送构建开始的消息到 Slack
    steps:
      # 发送开始构建的消息到 Slack
      - name: 发送开始构建的消息到 Slack（Send Build Start Message to Slack Channel）
        uses: slackapi/slack-github-action@v1.17.0
        if: github.event_name != 'pull_request'
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "《彷徨之街》宣传网站测试页开始通过 Azure 静态网站服务进行构建",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "===================\n构建开始\n名称: 彷徨之街宣传页正式网\n构建基于: `${{ github.event.ref }}` `${{ github.event.commits[0].id }}`"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: 构建和部署 Build And Deploy
    steps:
      # 代码签出
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: 设置 Node 环境（Setup Node）
        uses: actions/setup-node@v3
        with:
          node-version: 16
      # 获取 yarn 缓存目录
      - name: 获取 yarn 缓存目录
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      # 缓存依赖
      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      # 安装依赖
      - name: 安装依赖
        run: yarn --prefer-offline
      # 导出构建开始时间
      - name: 导出构建开始的时间 Export start time
        id: commit
        run: |
          echo "::set-output name=startTime::$(date +%s)"
      # 构建
      - name: 构建 Build
        id: build
        run: yarn build:stable
      # 导出构建完成的时间
      - name: 导出构建结束的时间 Export end time
        if: ${{ github.event_name != 'pull_request' }}
        id: endTime
        run: echo "::set-output name=time::$(nowtime=$(date +%s);echo $(expr $nowtime - ${{ steps.commit.outputs.startTime }}))"
      # 发送构建完成的消息到 Slack
      - name: Send Build Success Message to Slack Channel
        uses: slackapi/slack-github-action@v1.17.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "《彷徨之街》宣传网站测试页通过 Azure 静态网站服务构建成功",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "===================\n构建结束\n名称: 彷徨之街宣传页正式网\n是否成功: ${{ steps.build.outcome == 'success' }}\n花费时间: ${{ steps.endTime.outputs.time }}秒\n构建基于: `${{ github.event.ref }}` `${{ github.event.commits[0].id }}`"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
      - name: 部署到 aws Deploy on aws s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.PROD_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-1'
          SOURCE_DIR: 'dist'
      # 发送上传完成的消息到 Slack
      - name: Send upload done message to slack channel
        uses: slackapi/slack-github-action@v1.17.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "《彷徨之街》宣传网站测试页通过 Azure 静态网站服务构建成功",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "===================\n产物上传完成\n名称: 彷徨之街宣传页正式网\n是否成功: ${{ steps.upload_main.outcome == 'success' }}\n构建基于: `${{ github.event.ref }}` `${{ github.event.commits[0].id }}`"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
