name: 构建并上传至 Azure Blob

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  start_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: 发送构建开始的消息到 Slack
    steps:
      - run: |
          echo '${{ github.event.commits[0] }}'
      # 发送开始构建的消息到 Slack
      - name: 发送开始构建的消息到 Slack（Send Build Start Message to Slack Channel）
        uses: slackapi/slack-github-action@v1.17.0
        if: github.event_name != 'pull_request'
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "《彷徨之街》宣传网站测试页开始通过 Azure 静态网站服务进行构建",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "===================\n构建开始\n名称: 彷徨之街宣传页\n构建基于: `${{ github.event.ref }}` `${{ github.event.commits[0].id }}`\n提交消息: ${{ github.event.commits[0].messageHeadline }}（${{ github.event.commits[0].author.name }}）"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: 构建和部署 Build And Deploy
    steps:
      # 代码签出
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: 设置 Node 环境（Setup Node）
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 安装 Azure CLI
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli
          az version
      # 登录到 azure，为部署做好准备
      - name: 登录到 Azure（Login to Azure）
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_LOGIN_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_LOGIN_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_LOGIN_SUBSCRIPTION_ID }}

      # 获取 yarn 缓存目录
      - name: 获取 yarn 缓存目录
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      # 缓存依赖
      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      # 安装依赖
      - name: 安装依赖
        run: yarn --prefer-offline
      # 导出构建开始时间
      - name: 导出构建开始的时间 Export start time
        id: commit
        run: |
          echo "::set-output name=startTime::$(date +%s)"
      # 构建
      - name: 构建 Build
        id: build
        run: yarn build:uat
      # 导出构建完成的时间
      - name: 导出构建结束的时间 Export end time
        if: ${{ github.event_name != 'pull_request' }}
        id: endTime
        run: echo "::set-output name=time::$(nowtime=$(date +%s);echo $(expr $nowtime - ${{ steps.commit.outputs.startTime }}))"
      # 发送构建完成的消息到 Slack
      - name: Send Build Success Message to Slack Channel
        uses: slackapi/slack-github-action@v1.17.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "《彷徨之街》宣传网站测试页通过 Azure 静态网站服务构建成功",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "===================\n构建结束\n名称: 彷徨之街宣传页\n是否成功: ${{ steps.build.outcome == 'success' }}\n花费时间: ${{ steps.endTime.outputs.time }}秒\n构建基于: `${{ github.event.ref }}` `${{ github.event.commits[0].id }}`\n提交消息: ${{ github.event.commits[0].messageHeadline }}（${{ github.event.commits[0].author.name }}）"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
      # 上传主分支产物
      - name: 上传主分支产物
        id: upload_main
        if: ${{ github.event_name != 'pull_request' }}
        uses: azure/CLI@v1
        with:
          inlineScript: az storage blob upload-batch --account-name tsoastatictest --auth-mode key -d '$web' -s ./dist --overwrite
      # 上传 pr 产物
      - name: 上传 PR 产物
        id: upload_pr
        if: ${{ github.event_name == 'pull_request' }}
        uses: azure/CLI@v1
        with:
          inlineScript: az storage blob upload-batch --account-name tsoastatictestpreview --auth-mode key -d '$web' -s ./dist --overwrite
      # 清除主分支终结点
      - name: Purge CDN endpoint
        if: ${{ github.event_name != 'pull_request' }}
        uses: azure/CLI@v1
        with:
          inlineScript: az cdn endpoint purge --content-paths  "/*" --profile-name "tsoa-test-cdn" --name "tsoa-test" --resource-group "gushiji-mono-subprojects" --no-wait
      # 清除 pr 终结点
      - name: Purge CDN endpoint
        if: ${{ github.event_name == 'pull_request' }}
        uses: azure/CLI@v1
        with:
          inlineScript: az cdn endpoint purge --content-paths  "/*" --profile-name "tsoa-test-cdn" --name "tsoa-test-preview" --resource-group "gushiji-mono-subprojects" --no-wait
      # 发送上传完成的消息到 Slack
      - name: Send upload done message to slack channel
        uses: slackapi/slack-github-action@v1.17.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "《彷徨之街》宣传网站测试页通过 Azure 静态网站服务构建成功",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "===================\n产物上传完成\n名称: 彷徨之街宣传页\n是否成功: ${{ steps.upload_main.outcome == 'success' }}\n构建基于: `${{ github.event.ref }}` `${{ github.event.commits[0].id }}`\n提交消息: ${{ github.event.commits[0].messageHeadline }}（${{ github.event.commits[0].author.name }}）"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
      # 从 auzre 退出，消除登录状态
      - name: 从 Azure 退出（Login out from Azure）
        run: az logout
        if: always()
